### PR TITLE
Updating to 3.4.8

### PR DESCRIPTION
**Pull request by daniellockard**

### CODE REVIEW

**Comment by sherzberg** [comment]
Should we bump exhibitor too? https://github.com/Netflix/exhibitor/blob/v1.5.6/CHANGELOG.md

**Comment by daniellockard** [comment]
We use https://raw.githubusercontent.com/Netflix/exhibitor/d911a16d704bbe790d84bbacc655ef050c1f5806/exhibitor-standalone/src/main/resources/buildscripts/standalone/maven/pom.xml in the docker file which looks to pull in 1.5.5? 1.5.6 isn't released yet.

**Comment by sherzberg** [comment]
Ahhh. I just dug around on github tags...

:+1:

**Comment by lamdor** [comment]
going to build and publish up the docker image for this.

**Comment by lamdor** [comment]
```
$ docker push registry.banno-internal.com/zookeeper-exhibitor
The push refers to a repository [registry.banno-internal.com/zookeeper-exhibitor]
d42f0223369e: Pushed
d436c7dcd36a: Pushed
197ddfb84785: Pushed
5f70bf18a086: Pushed
603fd967d41c: Pushed
1.5.5_3.4.8: digest: sha256:4e038c9ee50bbf67605ec00f4cd618c87419e16b22afe5feb245e55bb073c687 size: 8732
d42f0223369e: Layer already exists
d436c7dcd36a: Layer already exists
197ddfb84785: Layer already exists
5f70bf18a086: Layer already exists
603fd967d41c: Layer already exists
latest: digest: sha256:dcea06c2f16462ea508cef247a8e602eee9675f8405db171e681485f49efa3d0 size: 8727
```

**Pull request merged**
